spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomprod
    username: postgres
    password: Arn@b123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8050
